name: test-terraform-module
run-name: ${{ github.actor }} iniciou o teste do modulo Terraform 🚀
on: 
  pull_request:
jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o codigo 
        uses: actions/checkout@v6
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}
